# Site settings
title: Lloyd Bennett
email: lloydbennett92@gmail.com
description: Lloyd Bennett's web design portfolio and blog site.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LloydBennett_
github_username:  LloydBennett
dribbble_username: ljbennett
linkedin_username: lloydbennett1
#paginate: 3
#paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown
permalink: /:title


collections:
  projects:
    output: true



# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lloyd Bennett"
      comments: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "casestudy"
      calltoaction: true
      inprogress: false

  -
    scope:
      path: ""
      type: "pages"
    values:
      calltoaction: true
