# Site settings
title: Lloyd Bennett
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LloydBennett_
github_username:  LloydBennett

# Build settings
markdown: kramdown
permalink: /:title


collections:
  projects:
    output: true



# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lloyd Bennett"

  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "casestudy"
